C:\Users\Yasunari Ota\Desktop\ssd_on_keras\ssd.py:40: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(64, (3, 3), activation="relu", name="conv1_1", padding="same")`
  name='conv1_1')(net['input'])
C:\Users\Yasunari Ota\Desktop\ssd_on_keras\ssd.py:44: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(64, (3, 3), activation="relu", name="conv1_2", padding="same")`
  name='conv1_2')(net['conv1_1'])
C:\Users\Yasunari Ota\Desktop\ssd_on_keras\ssd.py:46: UserWarning: Update your `MaxPooling2D` call to the Keras 2 API: `MaxPooling2D((2, 2), strides=(2, 2), name="pool1", padding="same")`
  name='pool1')(net['conv1_2'])
C:\Users\Yasunari Ota\Desktop\ssd_on_keras\ssd.py:51: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(128, (3, 3), activation="relu", name="conv2_1", padding="same")`
  name='conv2_1')(net['pool1'])
C:\Users\Yasunari Ota\Desktop\ssd_on_keras\ssd.py:55: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(128, (3, 3), activation="relu", name="conv2_2", padding="same")`
  name='conv2_2')(net['conv2_1'])
C:\Users\Yasunari Ota\Desktop\ssd_on_keras\ssd.py:57: UserWarning: Update your `MaxPooling2D` call to the Keras 2 API: `MaxPooling2D((2, 2), strides=(2, 2), name="pool2", padding="same")`
  name='pool2')(net['conv2_2'])
C:\Users\Yasunari Ota\Desktop\ssd_on_keras\ssd.py:62: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(256, (3, 3), activation="relu", name="conv3_1", padding="same")`
  name='conv3_1')(net['pool2'])
C:\Users\Yasunari Ota\Desktop\ssd_on_keras\ssd.py:66: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(256, (3, 3), activation="relu", name="conv3_2", padding="same")`
  name='conv3_2')(net['conv3_1'])
C:\Users\Yasunari Ota\Desktop\ssd_on_keras\ssd.py:70: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(256, (3, 3), activation="relu", name="conv3_3", padding="same")`
  name='conv3_3')(net['conv3_2'])
C:\Users\Yasunari Ota\Desktop\ssd_on_keras\ssd.py:72: UserWarning: Update your `MaxPooling2D` call to the Keras 2 API: `MaxPooling2D((2, 2), strides=(2, 2), name="pool3", padding="same")`
  name='pool3')(net['conv3_3'])
C:\Users\Yasunari Ota\Desktop\ssd_on_keras\ssd.py:77: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(512, (3, 3), activation="relu", name="conv4_1", padding="same")`
  name='conv4_1')(net['pool3'])
C:\Users\Yasunari Ota\Desktop\ssd_on_keras\ssd.py:81: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(512, (3, 3), activation="relu", name="conv4_2", padding="same")`
  name='conv4_2')(net['conv4_1'])
C:\Users\Yasunari Ota\Desktop\ssd_on_keras\ssd.py:85: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(512, (3, 3), activation="relu", name="conv4_3", padding="same")`
  name='conv4_3')(net['conv4_2'])
C:\Users\Yasunari Ota\Desktop\ssd_on_keras\ssd.py:87: UserWarning: Update your `MaxPooling2D` call to the Keras 2 API: `MaxPooling2D((2, 2), strides=(2, 2), name="pool4", padding="same")`
  name='pool4')(net['conv4_3'])
C:\Users\Yasunari Ota\Desktop\ssd_on_keras\ssd.py:92: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(512, (3, 3), activation="relu", name="conv5_1", padding="same")`
  name='conv5_1')(net['pool4'])
C:\Users\Yasunari Ota\Desktop\ssd_on_keras\ssd.py:96: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(512, (3, 3), activation="relu", name="conv5_2", padding="same")`
  name='conv5_2')(net['conv5_1'])
C:\Users\Yasunari Ota\Desktop\ssd_on_keras\ssd.py:100: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(512, (3, 3), activation="relu", name="conv5_3", padding="same")`
  name='conv5_3')(net['conv5_2'])
C:\Users\Yasunari Ota\Desktop\ssd_on_keras\ssd.py:102: UserWarning: Update your `MaxPooling2D` call to the Keras 2 API: `MaxPooling2D((3, 3), strides=(1, 1), name="pool5", padding="same")`
  name='pool5')(net['conv5_3'])
C:\Users\Yasunari Ota\Anaconda3\lib\site-packages\keras\legacy\layers.py:761: UserWarning: The `AtrousConvolution2D` layer  has been deprecated. Use instead the `Conv2D` layer with the `dilation_rate` argument.
  warnings.warn('The `AtrousConvolution2D` layer '
C:\Users\Yasunari Ota\Anaconda3\lib\site-packages\keras\legacy\layers.py:765: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(1024, (3, 3), activation="relu", name="fc6", dilation_rate=(6, 6), padding="same")`
  return Conv2D(*args, **kwargs)
C:\Users\Yasunari Ota\Desktop\ssd_on_keras\ssd.py:110: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(1024, (1, 1), activation="relu", name="fc7", padding="same")`
  border_mode='same', name='fc7')(net['fc6'])
C:\Users\Yasunari Ota\Desktop\ssd_on_keras\ssd.py:115: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(256, (1, 1), activation="relu", name="conv6_1", padding="same")`
  name='conv6_1')(net['fc7'])
C:\Users\Yasunari Ota\Desktop\ssd_on_keras\ssd.py:118: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(512, (3, 3), activation="relu", name="conv6_2", strides=(2, 2), padding="same")`
  name='conv6_2')(net['conv6_1'])
C:\Users\Yasunari Ota\Desktop\ssd_on_keras\ssd.py:122: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(128, (1, 1), activation="relu", name="conv7_1", padding="same")`
  name='conv7_1')(net['conv6_2'])
C:\Users\Yasunari Ota\Desktop\ssd_on_keras\ssd.py:126: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(256, (3, 3), activation="relu", name="conv7_2", strides=(2, 2), padding="valid")`
  name='conv7_2')(net['conv7_2'])
C:\Users\Yasunari Ota\Desktop\ssd_on_keras\ssd.py:130: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(128, (1, 1), activation="relu", name="conv8_1", padding="same")`
  name='conv8_1')(net['conv7_2'])
C:\Users\Yasunari Ota\Desktop\ssd_on_keras\ssd.py:133: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(256, (3, 3), activation="relu", name="conv8_2", strides=(2, 2), padding="same")`
  name='conv8_2')(net['conv8_1'])
WARNING:tensorflow:From C:\Users\Yasunari Ota\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:3148: calling l2_normalize (from tensorflow.python.ops.nn_impl) with dim is deprecated and will be removed in a future version.
Instructions for updating:
dim is deprecated, use axis instead
C:\Users\Yasunari Ota\Desktop\ssd_on_keras\ssd.py:140: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(12, (3, 3), name="conv4_3_norm_mbox_loc", padding="same")`
  name='conv4_3_norm_mbox_loc')(net['conv4_3_norm'])
C:\Users\Yasunari Ota\Desktop\ssd_on_keras\ssd.py:148: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(63, (3, 3), name="conv4_3_norm_mbox_conf", padding="same")`
  name=name)(net['conv4_3_norm'])
C:\Users\Yasunari Ota\Desktop\ssd_on_keras\ssd.py:160: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(24, (3, 3), name="fc7_mbox_loc", padding="same")`
  name='fc7_mbox_loc')(net['fc7'])
C:\Users\Yasunari Ota\Desktop\ssd_on_keras\ssd.py:168: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(126, (3, 3), name="fc7_mbox_conf", padding="same")`
  name=name)(net['fc7'])
C:\Users\Yasunari Ota\Desktop\ssd_on_keras\ssd.py:178: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(24, (3, 3), name="conv6_2_mbox_loc", padding="same")`
  name='conv6_2_mbox_loc')(net['conv6_2'])
C:\Users\Yasunari Ota\Desktop\ssd_on_keras\ssd.py:186: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(126, (3, 3), name="conv6_2_mbox_conf", padding="same")`
  name=name)(net['conv6_2'])
C:\Users\Yasunari Ota\Desktop\ssd_on_keras\ssd.py:197: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(24, (3, 3), name="conv7_2_mbox_loc", padding="same")`
  name='conv7_2_mbox_loc')(net['conv7_2'])
C:\Users\Yasunari Ota\Desktop\ssd_on_keras\ssd.py:205: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(126, (3, 3), name="conv7_2_mbox_conf", padding="same")`
  name=name)(net['conv7_2'])
C:\Users\Yasunari Ota\Desktop\ssd_on_keras\ssd.py:216: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(24, (3, 3), name="conv8_2_mbox_loc", padding="same")`
  name='conv8_2_mbox_loc')(net['conv8_2'])
C:\Users\Yasunari Ota\Desktop\ssd_on_keras\ssd.py:224: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(126, (3, 3), name="conv8_2_mbox_conf", padding="same")`
  name=name)(net['conv8_2'])
C:\Users\Yasunari Ota\Desktop\ssd_on_keras\ssd.py:258: UserWarning: The `merge` function is deprecated and will be removed after 08/2017. Use instead layers from `keras.layers.merge`, e.g. `add`, `concatenate`, etc.
  mode='concat', concat_axis=1, name='mbox_loc')
C:\Users\Yasunari Ota\Anaconda3\lib\site-packages\keras\legacy\layers.py:464: UserWarning: The `Merge` layer is deprecated and will be removed after 08/2017. Use instead layers from `keras.layers.merge`, e.g. `add`, `concatenate`, etc.
  name=name)
C:\Users\Yasunari Ota\Desktop\ssd_on_keras\ssd.py:265: UserWarning: The `merge` function is deprecated and will be removed after 08/2017. Use instead layers from `keras.layers.merge`, e.g. `add`, `concatenate`, etc.
  mode='concat', concat_axis=1, name='mbox_conf')
C:\Users\Yasunari Ota\Desktop\ssd_on_keras\ssd.py:273: UserWarning: The `merge` function is deprecated and will be removed after 08/2017. Use instead layers from `keras.layers.merge`, e.g. `add`, `concatenate`, etc.
  name='mbox_priorbox')
C:\Users\Yasunari Ota\Desktop\ssd_on_keras\ssd.py:288: UserWarning: The `merge` function is deprecated and will be removed after 08/2017. Use instead layers from `keras.layers.merge`, e.g. `add`, `concatenate`, etc.
  name='predictions')
train.py:257: UserWarning: The semantics of the Keras 2 argument `steps_per_epoch` is not the same as the Keras 1 argument `samples_per_epoch`. `steps_per_epoch` is the number of batches to draw from the generator at each epoch. Basically steps_per_epoch = samples_per_epoch/batch_size. Similarly `nb_val_samples`->`validation_steps` and `val_samples`->`steps` arguments have changed. Update your method calls accordingly.
  nb_worker=1)
train.py:257: UserWarning: Update your `fit_generator` call to the Keras 2 API: `fit_generator(<generator..., 80, 10, verbose=1, callbacks=[<keras.ca..., validation_data=<generator..., validation_steps=20, workers=1)`
  nb_worker=1)
C:\Users\Yasunari Ota\Anaconda3\lib\site-packages\tensorflow\python\ops\gradients_impl.py:97: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
